baseURL = 'http://maartenpeels.com/'
copyright = "2023 - {year}"
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'lowkey'
title = 'Maarten Peels'
enableRobotsTXT = true
summaryLength = 15
paginate = 10


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
