[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://ko-fi.com/maartenpeels"
    weight = 5
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/maartenpeels"
    weight = 3